name: Build and Publish Application to Docker Hub

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
  
    name: Build and Publish Docker Images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push Docker Image for Backend
      id: backend_build_push
      uses: docker/build-push-action@v4
      with:
        context: ../BackEnd
        file: ../Backend/Dockerfile
        push: true
        tags: chrschou/twc-weather-microservice:backend-${{ github.event.release.tag_name }}
        
    - name: Build and Push Docker Image for Frontend
      id: frontend_build_push
      uses: docker/build-push-action@v4
      with:
        context: ../FrontEnd
        file: ../FrontEnd/Dockerfile
        push: true
        tags: chrschou/twc-weather-microservice:frontend-${{ github.event.release.tag_name }}

